module.exports = {
  RPC_URL0: "https://t3rn-b2n.blockpi.network/v1/rpc/public",
  CHAIN_ID0: 334,
  SYMBOL0: "BRN",
  TX_EXPLORER0: "https://b2n.explorer.caldera.xyz/tx/",
  ADDRESS_EXPLORER0: "https://b2n.explorer.caldera.xyz/address/",
  RPC_URL1: "https://sepolia.drpc.org",
  CHAIN_ID1: 11155111,
  SYMBOL1: "ETH Sepolia",
  TX_EXPLORER1: "https://sepolia.etherscan.io/tx/",
  ADDRESS_EXPLORER1: "https://sepolia.etherscan.io/address/",
  RPC_URL2: "https://sepolia.optimism.io",
  CHAIN_ID2: 11155420,
  SYMBOL2: "OP Sepolia",
  TX_EXPLORER2: "https://optimism-sepolia.blockscout.com/tx/",
  ADDRESS_EXPLORER2: "https://optimism-sepolia.blockscout.com/address/",
  RPC_URL3: "https://sepolia-rollup.arbitrum.io/rpc",
  CHAIN_ID3: 421614,
  SYMBOL3: "ARB Sepolia",
  TX_EXPLORER3: "https://sepolia.arbiscan.io/tx/",
  ADDRESS_EXPLORER3: "https://sepolia.arbiscan.io/address/",
  RPC_URL4: "https://sepolia.base.org",
  CHAIN_ID4: 84532,
  SYMBOL4: "BASE Sepolia",
  TX_EXPLORER4: "https://sepolia.basescan.org/tx/",
  ADDRESS_EXPLORER4: "https://sepolia.basescan.org/address/",
  RPC_URL5: "https://sepolia.unichain.org",
  CHAIN_ID5: 1301,
  SYMBOL5: "UNI Sepolia",
  TX_EXPLORER5: "https://unichain-sepolia.blockscout.com/tx/",
  ADDRESS_EXPLORER5: "https://unichain-sepolia.blockscout.com/address/",
  RPC_URL6: "https://rpc.ankr.com/gravity",
  CHAIN_ID6: 1625,
  SYMBOL6: "G",
  TX_EXPLORER6: "https://explorer.gravity.xyz/tx/",
  ADDRESS_EXPLORER6: "https://explorer.gravity.xyz/address/",
  RPC_URL7: "https://api.infra.mainnet.somnia.network/",
  CHAIN_ID7: 5031,
  SYMBOL7: "SOMI",
  TX_EXPLORER7: "https://scan.somnia.network/tx/",
  ADDRESS_EXPLORER7: "https://scan.somnia.network/address/",
};
