module.exports = {
  RPC_URL0: "https://t3rn-b2n.blockpi.network/v1/rpc/public",
  CHAIN_ID0: 334,
  SYMBOL0: "BRN",
  TX_EXPLORER0: "https://b2n.explorer.caldera.xyz/tx/",
  ADDRESS_EXPLORER0: "https://b2n.explorer.caldera.xyz/address/",
  RPC_URL1: "",
  CHAIN_ID1: ,
  SYMBOL1: "ETH Sepolia",
  TX_EXPLORER1: "",
  ADDRESS_EXPLORER1: "",
  RPC_URL2: "",
  CHAIN_ID2: ,
  SYMBOL2: "ETH OP Sepolia",
  TX_EXPLORER2: "",
  ADDRESS_EXPLORER2: "",
  RPC_URL3: "",
  CHAIN_ID3: ,
  SYMBOL3: "ETH ARB Sepolia",
  TX_EXPLORER3: "",
  ADDRESS_EXPLORER3: "",
  RPC_URL4: "",
  CHAIN_ID4: ,
  SYMBOL4: "ETH BASE Sepolia",
  TX_EXPLORER4: "",
  ADDRESS_EXPLORER4: "",
};
